### ISSUE TITLE
FunctionType in ImageCanvas can return null

### ISSUE THREAD

**Issue by OlivierKamers** [hanreev/types-ol#21]
Is it possible to allow retuning null from the FunctionType in ImageCanvas? The source code checks the return value so returning null is a valid case. https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ol/source/ImageCanvas.d.ts#L14-L21

I asked the question on the OL repo too (https://github.com/openlayers/openlayers/pull/11451) but it seems too big of a refactor there to add stricter null checks. Are these types exactly synced with the OL jsdocs or can they be extended?

**Comment by hanreev** [comment]
@OlivierKamers 

after checking the source code i found that `canvasFunction` [option](https://github.com/openlayers/openlayers/blob/246aded8192391bbeb9034dbf260e84e0f9d58a3/src/ol/source/ImageCanvas.js#L30) for `ImageCanvasSource` is required and `FunctionType` must return `HTMLCanvasElement`

`canvasFuncion` will be called to generate new `HTMLCanvasElement` if needed [https://github.com/openlayers/openlayers/blob/246aded8192391bbeb9034dbf260e84e0f9d58a3/src/ol/source/ImageCanvas.js#L120](https://github.com/openlayers/openlayers/blob/246aded8192391bbeb9034dbf260e84e0f9d58a3/src/ol/source/ImageCanvas.js#L120)

the `FunctionType` may return `null` but it does not make sense because the `getImageInternal` method will always return `null`

**Comment by EvertEt** [comment]
I believe `getImageInternal` won't always return null. When the `canvasFunction` returns null, the current canvas will not be updated and the previously returned canvas will still be used.
This could be used to render heavy async operations:
render zoom level 1 -> render zoom level 2 (heavy) and return null -> 1 is still rendered -> 2 is ready and source is refreshed -> 2 is returned

**Comment by hanreev** [comment]
thanks for your explanation @EvertEt
the `canvasFunction` is required but may return a falsey value. I think `undefined` return will works without changing the definition. CMIIW

**Comment by EvertEt** [comment]
Thank you for your fast response.
Could you elaborate on how you see it working since the return type is `HTMLCanvasElement`?
I tried to change the returns to `undefined` but it resulted in the following error
![image](https://user-images.githubusercontent.com/9197891/93002443-6da8b200-f537-11ea-86cd-29e730a8456b.png)

**Comment by hanreev** [comment]
i got it working with `"strict": false` in `tsconfig.json`. i will fix the definition in the next release.
